# Generated by Django 4.1.2 on 2022-10-11 01:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_Title', models.CharField(max_length=200)),
                ('tutorial_Body', models.TextField()),
                ('tutorial_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
